"""mix_engine.blueprint — typed contract between mix agents and the .als writer.

Mirrors composition_engine.blueprint but for mix-side decisions: routing,
EQ corrections, dynamics, automation envelopes, mastering moves.

Phase 4.1 ships the foundation types + the diagnostic lane.
Phase 4.2 adds the eq_corrective lane (Tier A schema).
Other lanes materialize one-by-one as their producing agent gets built.
"""
from __future__ import annotations

from mix_engine.blueprint.schema import (
    DYN_ATTACK_MAX_MS,
    DYN_ATTACK_MIN_MS,
    DYN_CEILING_MAX_DB,
    DYN_CEILING_MIN_DB,
    DYN_DRY_WET_MAX,
    DYN_DRY_WET_MIN,
    DYN_KNEE_MAX_DB,
    DYN_KNEE_MIN_DB,
    DYN_MAKEUP_MAX_DB,
    DYN_MAKEUP_MIN_DB,
    DYN_RATIO_MAX,
    DYN_RATIO_MIN,
    DYN_RELEASE_MAX_MS,
    DYN_RELEASE_MIN_MS,
    DYN_SIDECHAIN_DEPTH_MAX_DB,
    DYN_SIDECHAIN_DEPTH_MIN_DB,
    DYN_THRESHOLD_MAX_DB,
    DYN_THRESHOLD_MIN_DB,
    DYN_TRANSIENTS_MAX,
    DYN_TRANSIENTS_MIN,
    EQ_FREQ_MAX_HZ,
    EQ_FREQ_MIN_HZ,
    EQ_GAIN_MAX_DB,
    EQ_GAIN_MIN_DB,
    EQ_Q_MAX,
    EQ_Q_MIN,
    KNOWN_CDE_ISSUE_TYPES,
    MIX_LANES,
    Anomaly,
    BandConflict,
    CDECorrectionRecipe,
    CDEDiagnostic,
    CDEMeasurement,
    CDETFPContext,
    DiagnosticReport,
    DynamicsAutomationPoint,
    DynamicsCorrection,
    DynamicsCorrectiveDecision,
    EQAutomationPoint,
    EQBandCorrection,
    EQCorrectiveDecision,
    FreqConflictsMetadata,
    FullMixMetrics,
    HealthScore,
    MixBlueprint,
    MixCitation,
    MixDecision,
    SidechainConfig,
    TrackInfo,
    DEPRECATED_CHAIN_POSITIONS_REDIRECT,
    VALID_CDE_APPLICATION_STATUSES,
    VALID_CDE_CONFIDENCES,
    VALID_CDE_SEVERITIES,
    VALID_CHAIN_POSITIONS,
    VALID_DYNAMICS_CHAIN_POSITIONS,
    VALID_DYNAMICS_DEVICES,
    VALID_DYNAMICS_TYPES,
    VALID_EQ_BAND_TYPES,
    VALID_EQ_INTENTS,
    VALID_FILTER_SLOPES_DB_PER_OCT,
    VALID_PROCESSING_MODES,
    VALID_SIDECHAIN_MODES,
)
from mix_engine.blueprint.agent_parsers import (
    MixAgentOutputError,
    SUPPORTED_DIAGNOSTIC_SCHEMA_VERSIONS,
    SUPPORTED_DYNAMICS_CORRECTIVE_SCHEMA_VERSIONS,
    SUPPORTED_EQ_CORRECTIVE_SCHEMA_VERSIONS,
    VALID_ANOMALY_SEVERITIES,
    VALID_CITATION_KINDS,
    VALID_TRACK_TYPES,
    extract_json_payload,
    parse_diagnostic_decision,
    parse_diagnostic_decision_from_response,
    parse_dynamics_corrective_decision,
    parse_dynamics_corrective_decision_from_response,
    parse_eq_corrective_decision,
    parse_eq_corrective_decision_from_response,
)

__all__ = [
    "MIX_LANES",
    # Foundation types
    "Anomaly",
    "DiagnosticReport",
    "FullMixMetrics",
    "HealthScore",
    "MixAgentOutputError",
    "MixBlueprint",
    "MixCitation",
    "MixDecision",
    "TrackInfo",
    # Phase 4.2.8 — CDE + Freq Conflicts absorption
    "BandConflict",
    "CDECorrectionRecipe",
    "CDEDiagnostic",
    "CDEMeasurement",
    "CDETFPContext",
    "FreqConflictsMetadata",
    "KNOWN_CDE_ISSUE_TYPES",
    "VALID_CDE_APPLICATION_STATUSES",
    "VALID_CDE_CONFIDENCES",
    "VALID_CDE_SEVERITIES",
    # EQ corrective lane (Phase 4.2)
    "EQ_FREQ_MAX_HZ",
    "EQ_FREQ_MIN_HZ",
    "EQ_GAIN_MAX_DB",
    "EQ_GAIN_MIN_DB",
    "EQ_Q_MAX",
    "EQ_Q_MIN",
    "EQAutomationPoint",
    "EQBandCorrection",
    "EQCorrectiveDecision",
    "DEPRECATED_CHAIN_POSITIONS_REDIRECT",
    "VALID_CHAIN_POSITIONS",
    "VALID_EQ_BAND_TYPES",
    "VALID_EQ_INTENTS",
    "VALID_FILTER_SLOPES_DB_PER_OCT",
    "VALID_PROCESSING_MODES",
    # Dynamics corrective lane (Phase 4.3)
    "DYN_ATTACK_MAX_MS",
    "DYN_ATTACK_MIN_MS",
    "DYN_CEILING_MAX_DB",
    "DYN_CEILING_MIN_DB",
    "DYN_DRY_WET_MAX",
    "DYN_DRY_WET_MIN",
    "DYN_KNEE_MAX_DB",
    "DYN_KNEE_MIN_DB",
    "DYN_MAKEUP_MAX_DB",
    "DYN_MAKEUP_MIN_DB",
    "DYN_RATIO_MAX",
    "DYN_RATIO_MIN",
    "DYN_RELEASE_MAX_MS",
    "DYN_RELEASE_MIN_MS",
    "DYN_SIDECHAIN_DEPTH_MAX_DB",
    "DYN_SIDECHAIN_DEPTH_MIN_DB",
    "DYN_THRESHOLD_MAX_DB",
    "DYN_THRESHOLD_MIN_DB",
    "DYN_TRANSIENTS_MAX",
    "DYN_TRANSIENTS_MIN",
    "DynamicsAutomationPoint",
    "DynamicsCorrection",
    "DynamicsCorrectiveDecision",
    "SidechainConfig",
    "VALID_DYNAMICS_CHAIN_POSITIONS",
    "VALID_DYNAMICS_DEVICES",
    "VALID_DYNAMICS_TYPES",
    "VALID_SIDECHAIN_MODES",
    # Schema versions + canonical enums
    "SUPPORTED_DIAGNOSTIC_SCHEMA_VERSIONS",
    "SUPPORTED_DYNAMICS_CORRECTIVE_SCHEMA_VERSIONS",
    "SUPPORTED_EQ_CORRECTIVE_SCHEMA_VERSIONS",
    "VALID_ANOMALY_SEVERITIES",
    "VALID_CITATION_KINDS",
    "VALID_TRACK_TYPES",
    # Parsers
    "extract_json_payload",
    "parse_diagnostic_decision",
    "parse_diagnostic_decision_from_response",
    "parse_dynamics_corrective_decision",
    "parse_dynamics_corrective_decision_from_response",
    "parse_eq_corrective_decision",
    "parse_eq_corrective_decision_from_response",
]
